### ISSUE TITLE
The PVP should include advice about SafeHaskell

### ISSUE THREAD

**Issue by andreasabel** [haskell/pvp#44] opened 2022-11-20 16:23 UTC
The PVP does at the moment not give any advice about SafeHaskell.  E.g. it does not say that if you make a previously `Safe` module unsafe, then you need a major version bump.  
Why major bump?  Because then `import safe` statements suddenly error out, and downstream packages become unbuildable.

In the wild:
- https://github.com/haskell/directory/issues/147

In `directory-1.3.8.0`, the module `System.Directory` is no longer `Safe`, as it used to be in `1.3.7.*`.  Thus the new release should rather have been `directory-1.4.0.0`.  Being released as `1.3.8.0`, packages using `directory < 1.4` and `import safe System.Directory` are now broken and need a revision.

**Comment by phadej** [comment] 2022-11-20 16:37
Is this duplicate of #22

**Comment by phadej** [comment] 2022-11-29 09:31
Closing as duplicate of #22

**Closed by phadej** 2022-11-29 09:31 UTC
